name: Java CI with Maven and SonarCloud

on:
  push:
    branches: [ Luis-1 ]
  pull_request:
    branches: [ Luis-1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Install Xvfb
      run: sudo apt-get update && sudo apt-get install -y xvfb

    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Build and test
      run: mvn clean verify -Djava.awt.headless=false

    # Ejecutar los analizadores estáticos
    - name: Run Checkstyle
      run: mvn verify checkstyle:checkstyle

    - name: Run PMD
      run: mvn verify pmd:pmd

    - name: Run SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.projectKey=LuisBuilds11_jpacman-framework -Dsonar.organization=luisbuilds11 -Dsonar.host.url=https://sonarcloud.io

      # Subir reportes como artefactos
    - name: Upload static analysis reports
      uses: actions/upload-artifact@v4
      with:
        name: static-analysis-reports
        path: |
          target/site/checkstyle.html
          target/site/pmd.html
          target/site/jacoco/index.html

