name: Java CI with Maven and SonarCloud

on:
  push:
    branches: [ Luis-1 ]
  pull_request:
    branches: [ Luis-1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Maven options
        run: echo MAVEN_OPTS=-Xmx1024m >> $GITHUB_ENV

      - name: Set up headless mode for Java
        run: echo JAVA_TOOL_OPTIONS=-Djava.awt.headless=true >> $GITHUB_ENV

      - name: Build and test
        run: mvn clean verify

      - name: Run SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar \
             -Dsonar.projectKey=LuisBuilds11_jpacman \
             -Dsonar.organization=luisbuilds11 \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.java.coveragePlugin=jacoco \
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
