name: Java CI with Maven and SonarCloud

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # GitHub Actions token
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     # Tu token de SonarCloud

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and run tests
      run: mvn clean verify

    - name: Run SonarCloud analysis
      run: mvn sonar:sonar \
        -Dsonar.projectKey=LuisBuilds11_jpacman-framework \
        -Dsonar.organization=luisbuilds11-1 \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/

    - name: Upload JaCoCo coverage report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: target/site/jacoco/
